model dsmodelIterationSelect
  extends ThermalSystemsControlLib.Applications.ETA_Factory.ETAFactory_HeatingSystems;
  annotation(__Dymola_SimulationIterationVariables={"HNHT.StaticHeatingSystem.RV350.threeWayValve_Physical.valveLinear.dp",
   "HNHT.StaticHeatingSystem.SV.twoWayValve_Physical.valveLinear.dp", 
  "HNHT_HNLT.HeatExchanger1System.RV315.threeWayValve_Physical.valveLinear1.dp",
   "HNHT.CentralMachineHeatingSystem.SV300.twoWayValve_Physical.valveLinear.dp",
   "HNHT_HNLT.HeatExchanger1System.RV315.threeWayValve_Physical.valveLinear.dp",
   "HNHT.StaticHeatingSystem.RV350.threeWayValve_Physical.valveLinear1.dp", 
  "HNHT.CondensingBoilerSystem.RV331.threeWayValve_Physical.valveLinear1.dp", 
  "HNHT.CondensingBoilerSystem.RV331.threeWayValve_Physical.valveLinear.dp", 
  "HNHT.CHP1System.RV32x.threeWayValve_Physical.valveLinear1.dp", 
  "HNHT.CHP1System.RV32x.threeWayValve_Physical.valveLinear.dp", 
  "HNHT.CHP2System.RV32x.threeWayValve_Physical.valveLinear.dp", 
  "HNHT.CHP2System.RV32x.threeWayValve_Physical.valveLinear1.dp", 
  "HNHT.VSIStorageSystem.SV306.threeWayValve_Physical.valveLinear1.dp", 
  "HNHT.VSIStorageSystem.SV307.twoWayValve_Physical.valveLinear.dp", 
  "HNHT.VSIStorageSystem.SV306.threeWayValve_Physical.valveLinear.dp", 
  "HNHT.VSIStorageSystem.SV305.threeWayValve_Physical.valveLinear.dp", 
  "HNHT_HNLT.HeatPump1System.RV342.threeWayValve_Physical.valveLinear1.dp", 
  "HNHT_HNLT.HeatPump1System.RV342.threeWayValve_Physical.valveLinear.dp", 
  "HNHT_HNLT.HeatPump1System.RV242.threeWayValve_Physical.valveLinear1.dp", 
  "HNHT_HNLT.HeatPump1System.RV242.threeWayValve_Physical.valveLinear.dp", 
  "HNLT_CN.InnerCapillaryTubeMats.HeatExchanger3.volume1.medium.p", 
  "HNLT_CN.InnerCapillaryTubeMats.SV.twoWayValve_Physical.valveLinear.dp", 
  "HNLT_CN.InnerCapillaryTubeMats.RV500.threeWayValve_Physical.valveLinear1.dp",
   "HNLT_CN.InnerCapillaryTubeMats.HeatExchanger3.volume2.medium.p", 
  "HNLT_CN.InnerCapillaryTubeMats.SVHNLT_CN.threeWayValve_Physical.valveLinear1.dp",
   "HNLT_CN.InnerCapillaryTubeMats.SVHNLT_CN.threeWayValve_Physical.valveLinear.dp",
   "HNLT_CN.InnerCapillaryTubeMats.SV1.threeWayValve_Physical.valveLinear.dp", 
  "HNLT_CN.InnerCapillaryTubeMats.SV1.threeWayValve_Physical.valveLinear1.dp", 
  "CN.eChillerSystem.SV138.twoWayValve_Physical.valveLinear.dp", 
  "HNLT_CN.UnderfloorHeatingSystem.RV425.threeWayValve_Physical.volume.medium.p",
   "HNLT_CN.UnderfloorHeatingSystem.SV.twoWayValve_Physical.valveLinear.dp", 
  "HNLT_CN.UnderfloorHeatingSystem.SV423.threeWayValve_Physical.valveLinear.dp",
   "HNLT_CN.UnderfloorHeatingSystem.SV423.threeWayValve_Physical.valveLinear1.dp",
   "HNLT_CN.UnderfloorHeatingSystem.SV424.threeWayValve_Physical.valveLinear1.dp",
   "HNLT_CN.UnderfloorHeatingSystem.RV425.threeWayValve_Physical.valveLinear1.dp",
   "HNLT_CN.UnderfloorHeatingSystem.SV424.threeWayValve_Physical.valveLinear.dp",
   "CN.HVFASystem.SVx05.threeWayValve_Physical.valveLinear1.dp", 
  "CN.HVFASystem.SVx06.threeWayValve_Physical.valveLinear1.dp", "CN.HVFASystem.SVx06.threeWayValve_Physical.valveLinear.dp",
   "CN.HVFASystem.RVx05.threeWayValve_Physical.valveLinear1.dp", 
  "CN.HVFASystem.RVx05.threeWayValve_Physical.valveLinear.dp", "CN.HVFASystem.SVx05.threeWayValve_Physical.valveLinear.dp",
   "CN.CentralMachineCoolingSystem.SV100.twoWayValve_Physical.valveLinear.dp", 
  "HNLT_CN.HeatPump2System.SV146.twoWayValve_Physical.valveLinear.dp", 
  "HNLT_CN.HeatPump2System.SV246.twoWayValve_Physical.valveLinear.dp", 
  "HNLT.OuterCapillaryTubeMats.SV235.twoWayValve_Physical.valveLinear.dp", 
  "HNLT.CompressorSystem.RV251.threeWayValve_Physical.valveLinear.dp", 
  "HNLT.CompressorSystem.RV251.threeWayValve_Physical.valveLinear1.dp", 
  "HNLT.HVFASystem.SVx05.threeWayValve_Physical.valveLinear1.dp", 
  "HNLT.HVFASystem.RVx05.threeWayValve_Physical.valveLinear1.dp", 
  "HNLT.HVFASystem.RVx05.threeWayValve_Physical.valveLinear.dp", 
  "HNLT.HVFASystem.SVx05.threeWayValve_Physical.valveLinear.dp", 
  "HNLT.HVFASystem.SVx06.threeWayValve_Physical.valveLinear.dp", 
  "HNLT.HVFASystem.SVx06.threeWayValve_Physical.valveLinear1.dp", 
  "HNHT_HNLT.HeatExchanger1System.SV215.twoWayValve_Physical.valveLinear.dp", 
  "der(HNLT.OuterCapillaryTubeMats.HeatExchanger6.volume1.medium.T)", 
  "der(HNLT.OuterCapillaryTubeMats.OuterCapillaryTubeMats.volume.medium.T)", 
  "der(HNLT.OuterCapillaryTubeMats.RV600.threeWayValve_Physical.volume.medium.T)",
   "HNLT.OuterCapillaryTubeMats.RV600.threeWayValve_Physical.valveLinear.dp", 
  "HNLT.OuterCapillaryTubeMats.RV600.threeWayValve_Physical.valveLinear1.dp", 
  "CN.HVFASystem.HVFAStorage.port_a.m_flow", "HNLT.HVFASystem.HVFAStorage.port_a.m_flow"});
end dsmodelIterationSelect;
